"""
Django settings for onlineretailpos project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]
PROJECT_DIR = os.path.join(BASE_DIR, "onlineretailpos")

CART_SESSION_ID = 'cart'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# Application definition
import importlib

INSTALLED_APPS = [
    "jazzmin",  # admin theme; must come before the admin app
    "colorfield",
    'onlineretailpos.admin.MyAdminConfig',#'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'mathfilters',
    'inventory',
    'transaction',
    'cart',
    'stores',
    'onlineretailpos.apps.OnlineRetailPOSConfig',
]

# Optional admin convenience apps: django-import-export needs tablib[ods]
# -> odfpy, which has no binary wheel and cannot install on build-locked
# hosts (e.g. Vercel). They activate only when installed.
for _optional_app in ('import_export', 'rangefilter', 'django_admin_logs'):
    try:
        importlib.import_module(_optional_app)
        INSTALLED_APPS.append(_optional_app)
    except ImportError:
        pass


# Sessions and sales always use the database (default DB-backed sessions).
# Serverless hosts like Vercel have read-only filesystems, so deploying there
# requires an external database (NAME_OF_DATABASE=postgres / DATABASE_URL).

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'stores.access.StoreMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

ROOT_URLCONF = 'onlineretailpos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_DIR, "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'onlineretailpos.context_processors.branding',
                'stores.access.branch_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlineretailpos.wsgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATIC_URL = f"/static/"
STATICFILES_DIRS = (
    os.path.join(PROJECT_DIR,'static'),
)
# MEDIA_URL = 'media/'
# MEDIA_ROOT = Path.joinpath(PROJECT_DIR, "media/")
# # Assets Management
# ASSETS_ROOT = Path.joinpath(STATIC_ROOT,'assets/')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Admin theme (django-jazzmin). STORE_NAME is defined in the environment-
# specific settings module, so read the env var directly here.
# ---------------------------------------------------------------------------
_ADMIN_BRAND = os.getenv("STORE_NAME", "Stitch the Pret")

LOW_STOCK_THRESHOLD = int(os.getenv("LOW_STOCK_THRESHOLD", 5))

JAZZMIN_SETTINGS = {
    "site_title": f"{_ADMIN_BRAND} Admin",
    "site_header": _ADMIN_BRAND,
    "site_brand": _ADMIN_BRAND,
    "site_logo": "img/logo.svg",
    "login_logo": "img/logo.svg",
    "site_logo_classes": "",
    "site_icon": "img/logo.svg",
    "welcome_sign": f"Sign in to {_ADMIN_BRAND} Data Portal",
    "copyright": _ADMIN_BRAND,
    "search_model": ["inventory.product"],
    "user_avatar": None,

    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "Open POS", "url": "home", "new_window": True},
        {"model": "inventory.product"},
        {"name": "Transfers", "url": "transfer_list", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Open POS", "url": "register", "new_window": True, "icon": "fas fa-cash-register"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "inventory", "inventory.product", "inventory.department", "inventory.tax", "inventory.deposit",
        "stores", "stores.store", "stores.storemembership", "stores.branchstock", "stores.stocktransfer", "stores.stockmovement",
        "transaction", "cart", "auth",
    ],
    "custom_links": {
        "stores": [
            {"name": "New transfer (POS)", "url": "transfer_new", "icon": "fas fa-exchange-alt",
             "permissions": ["stores.view_stocktransfer"]},
            {"name": "Stock levels (POS)", "url": "stock_levels", "icon": "fas fa-boxes",
             "permissions": ["stores.view_branchstock"]},
            {"name": "Receive stock (POS)", "url": "inventory_add", "icon": "fas fa-dolly",
             "permissions": ["stores.view_branchstock"]},
        ],
        "inventory": [{
            "name": "Upload stock (.xlsx)",
            "url": "admin:inventory_product_stock_upload",
            "icon": "fas fa-file-upload",
            "permissions": ["inventory.add_product"],
        }],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "inventory.product": "fas fa-tshirt",
        "inventory.department": "fas fa-layer-group",
        "inventory.tax": "fas fa-percent",
        "inventory.deposit": "fas fa-coins",
        "transaction.transaction": "fas fa-receipt",
        "transaction.productTransaction": "fas fa-list-ul",
        "cart.displayed_items": "fas fa-th-large",
        "django_admin_logs.LogEntry": "fas fa-history",
        "stores": "fas fa-store",
        "stores.store": "fas fa-store",
        "stores.storemembership": "fas fa-id-badge",
        "stores.branchstock": "fas fa-boxes",
        "stores.stocktransfer": "fas fa-exchange-alt",
        "stores.stockmovement": "fas fa-history",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "changeform_format": "single",
    "show_ui_builder": False,
    "custom_css": "css/admin_theme.css",
    "custom_js": "js/admin_theme.js",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    # No dark_mode_theme: Jazzmin's OS-following dark theme turns text white while
    # cards/pages stay light, making text unreadable. Keep the admin light.
    "dark_mode_theme": None,
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_child_indent": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
