"""
Django settings for onlineretailpos project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]
PROJECT_DIR = os.path.join(BASE_DIR, "onlineretailpos")

CART_SESSION_ID = 'cart'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# Application definition
import importlib

INSTALLED_APPS = [
    # "admin_interface", #Interface if Admin Port Customization is needed
    "colorfield",
    'onlineretailpos.admin.MyAdminConfig',#'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'mathfilters',
    'inventory',
    'transaction',
    'cart',
    # Loads last so its ready() runs after django.contrib.auth's, letting it
    # disconnect the last_login signal in read-only-DB mode (see apps.py).
    'onlineretailpos.apps.OnlineRetailPOSConfig',
]

# Optional admin convenience apps: django-import-export needs tablib[ods]
# -> odfpy, which has no binary wheel and cannot install on build-locked
# hosts (e.g. Vercel). They activate only when installed.
for _optional_app in ('import_export', 'rangefilter', 'django_admin_logs'):
    try:
        importlib.import_module(_optional_app)
        INSTALLED_APPS.append(_optional_app)
    except ImportError:
        pass


# Read-only-filesystem hosts (Vercel serverless functions) running the baked-in
# sqlite file: keep login working with signed-cookie sessions (no DB write),
# skip the last_login update, and let views stash completed sales in the
# session. A real database (NAME_OF_DATABASE=postgres) is writable, so it gets
# normal DB-backed sessions and persisted transactions.
_using_baked_sqlite = os.getenv('NAME_OF_DATABASE', 'sqlite') == 'sqlite'
_on_read_only_host = (os.getenv('VERCEL')
                      or os.getenv('READ_ONLY_DB', '').lower() in ('1', 'true', 'yes'))
if _using_baked_sqlite and _on_read_only_host:
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
    # Flag for views: the sqlite file cannot be written, so completed sales
    # are kept in the (cookie) session instead of the DB.
    READ_ONLY_DATABASES = True
    # The update_last_login signal is disconnected in
    # onlineretailpos/apps.py ready(), which runs after auth's ready().

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

ROOT_URLCONF = 'onlineretailpos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_DIR, "templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlineretailpos.wsgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATIC_URL = f"/static/"
STATICFILES_DIRS = (os.path.join(PROJECT_DIR,'static'),)
# MEDIA_URL = 'media/'
# MEDIA_ROOT = Path.joinpath(PROJECT_DIR, "media/")
# # Assets Management
# ASSETS_ROOT = Path.joinpath(STATIC_ROOT,'assets/')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


